-- =============================================================================
-- todocli Supabase Database Schema
-- Run this script in your Supabase Project -> SQL Editor -> New Query -> Run
-- =============================================================================

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    password_salt TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tasks Table
CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL REFERENCES users(username) ON DELETE CASCADE,
    task_name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Indexes for fast lookup and deterministic ordering
CREATE INDEX IF NOT EXISTS idx_tasks_username_id ON tasks(username, id ASC);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;

-- 5. Access Policies (Permit public anon client operations for todocli CLI)
-- Users policies
DROP POLICY IF EXISTS "Allow public select users" ON users;
CREATE POLICY "Allow public select users" ON users FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert users" ON users;
CREATE POLICY "Allow public insert users" ON users FOR INSERT WITH CHECK (true);

-- Tasks policies
DROP POLICY IF EXISTS "Allow public select tasks" ON tasks;
CREATE POLICY "Allow public select tasks" ON tasks FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert tasks" ON tasks;
CREATE POLICY "Allow public insert tasks" ON tasks FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public delete tasks" ON tasks;
CREATE POLICY "Allow public delete tasks" ON tasks FOR DELETE USING (true);

DROP POLICY IF EXISTS "Allow public update tasks" ON tasks;
CREATE POLICY "Allow public update tasks" ON tasks FOR UPDATE USING (true);
